export const URL_PARAM_ROOM = 'roomId'
export const CARD_VALUES = ['0', '1', '2', '3', '5', '8', '13', '21', '34', '55', '89', '?', '☕']
export const CARD_VALUE_NOT_VISIBLE = '**'
export const STORAGE_USER_ID = 'scrum-poker-online'
export const TEXT_SELECT_ISSUE_NO_ADMIN = 'Tell the admin to select an issue!'
export const TEXT_SELECT_ISSUE_ADMIN = 'Select an issue!'
export const TEXT_SELECT_CARD = 'Select a card!'
export const CUSTOM_EXCEPTION_TEXT = 'HubException: '
export const UNCONTROLLED_ERROR = '😭 Uncontrolled error, try it later 😭'